#.
#Settings for the dash effect
[dash]
	#.
	#The multiplier for the dash delta movement
	#Range: 0 ~ 100
	dashDeltaModifier = 2
	#.
	#Enable dash from the Effect of Estrogen
	dashEnabled = true
#.
#Settings for the centrifuge
[centrifuge]
	#.
	#Minimum speed required for the centrifuge to work
	#[@cui:RequiresReload:both]
	#Range: 0.0 ~ 256.0
	centrifugeSpeedRequired = 256.0
